<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="ru" xml:lang="ru">
<head>
  <title>Мир желаний</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="description" content="Мир желаний"/>
  <script type="text/javascript">
    function setCookie (name, value, expires, path, domain, secure) {
      document.cookie = name + "=" + escape(value) +
        ((expires) ? "; expires=" + expires : "") +
        ((path) ? "; path=" + path : "") +
        ((domain) ? "; domain=" + domain : "") +
        ((secure) ? "; secure" : "");
    }

    if (self.parent.frames.length == 0 && '<?php echo $this->referer;?>') {
      setCookie('redirect', document.location.href, new Date(), '/');
      document.location.href = '<?php echo $this->referer;?>/app<?php echo $this->app_id;?>';
    }
  </script>
</head>
<body>
</body>
</html>