<div id="menu">
	<a onclick="Common.url('/')" <?php echo ($this->main)? 'class="selected"':'';?>>Главная</a>
	<span class="divider">|</span>
	<a onclick="Common.url('/intention/my')" <?php echo ($this->my)? 'class="selected"':'';?>>Мои желания</a>
	<span class="divider">|</span>
	<a onclick="Common.url('/user/rating')" <?php echo ($this->ratingpage)? 'class="selected"':'';?>>Таблица рейтингов</a>
	<span class="divider">|</span>
<?php if ($this->admin) { ?>
	<a onclick="Common.url('/story/index')" <?php echo ($this->story)? 'class="selected"':'';?>><b>Верю, не верю</b></a>
	<span class="divider">|</span>
<?php } ?>
	<a style="color:red" onclick="Common.url('/intention/tender')" <?php echo ($this->tenderpage)? 'class="selected"':'';?>>Конкурс (Бесплатные голоса)</a>

	<a class="fl_r" onclick="Common.url('/index/authors')" <?php echo ($this->my)? 'class="selected"':'';?>>Авторы</a>
</div>
