<?php echo $this->partial('_blocks/menu.phtml', array('tenderpage'=>1));?>
<?php if($this->authorsCheck): ?>
<a href="/index/notification" class="fl_r">Рассылка</a>
<?php endif; ?>
<div class="clear_fix"></div>
<div id="main">
  <div class="clear_fix"></div>
  <?php echo Model_Users::getBannerh();?>
	<div class="module_header">Конкурс</div>
	<div class="text">
      <p><b>Новые правила:</b>
      <ul style="margin-top:0;margin-bottom:0;">
      <li>Расскажи свою историю как ты проводишь время с новыми друзьями или с любимым человеком. ПОЛУЧИ В ПОДАРОК ГОЛОСА.</li>
      <li><b>За каждые полные 100 лайков вашей истории вы ГАРАНТИРОВАНО получает по 1 голосу.</b></li>
      </ul>
      <p>Помоги развитию приложения: <a onclick='VK.callMethod("showInviteBox");'>Пригласи друзей</a>,
          <a href="http://cl.cpaevent.ru/51308f647355383e1c000004/" target="_blank">Найди новых друзей</a> или просто <b>кликни по баннеру вверху</b>.<br/>
          Количество голосов за историю будет расти с вашей же помощью.
      </p>
  </div>
  <div class="clear_fix"></div>
<!--    <div id="vk_poll"></div>-->

	<div id="vk_comments"></div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		Common.intentionViewUid('Author');
	})
  VK.Widgets.Comments("vk_comments", {limit: 5, width: "590", attach: "*", pageUrl:'<?php echo $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]; ?>'});
//  VK.Widgets.Poll("vk_poll", {width: "590"}, "55827243_acb58cf3a5cb9c65d4");
</script>